db:
  image: postgres
  container_name: tasks_db
  restart: always
  environment:
    POSTGRES_USER: user_tasks
    POSTGRES_PASSWORD: password_tasks
    POSTGRES_DB: tasks_management
  volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # <--- AUTO-EXECUÇÃO
    - sellflux_tasks_data:/var/lib/postgresql/data
  ports:
    - "5432:5432"